# Generated by Django 6.1 on 2026-08-18 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="dateinvite",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
        ),
        migrations.AddField(
            model_name="dateinvite",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_invites",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Получатель",
            ),
        ),
        migrations.AddField(
            model_name="profilephoto",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="profilereaction",
            name="from_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_reactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто оценил",
            ),
        ),
        migrations.AddField(
            model_name="profilereaction",
            name="to_user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_reactions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кого оценили",
            ),
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="viewed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="was_viewed_by",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Смотрели",
            ),
        ),
        migrations.AddField(
            model_name="viewhistory",
            name="viewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="view_history",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Смотрел",
            ),
        ),
        migrations.AddConstraint(
            model_name="dateinvite",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user", "invite_type"), name="unique_invite"
            ),
        ),
        migrations.AddConstraint(
            model_name="profilereaction",
            constraint=models.UniqueConstraint(
                fields=("from_user", "to_user"), name="unique_user_reaction"
            ),
        ),
    ]
